version: "3.4"

services:
  db:
    image: mysql
    container_name: mysql-local
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --local-infile=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - "${MYSQL_HOST_PORT}:3306"
  flyway:
    image: flyway/flyway
    container_name: flyway-local
    command: -url=jdbc:mysql://db:3306/sys?useSSL=false -user=root -password=P@ssw0rd -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
      - ./data/scripts:/flyway/sql
    depends_on:
      - db
